url: https://y7kim.github.io
baseurl: /clinica-pies/

# Site settings
title: ClinicaPies
email: clinicapies.brunete@gmail.com
description: "Clínica de podología"


# Team names, titles and social links
people:
- name: María Gallego Pizarro
  pic: 1
  position: Podóloga jefa
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Calle Real de San Sebastián, 23
  - line: Brunete, Madrid (28690)

# Services
services:
  - description: Es el engrosamiento excesivo de la capa más externa de la piel (estrato córneo) causado por un aumento en la producción de queratina. En podología, suele manifestarse como áreas de piel endurecida, como callosidades o durezas, especialmente en zonas sometidas a presión o fricción repetida.
    title: DUREZAS 
    subtitle: (HIPERQUERATOSIS)
    picname: durezas_hiperqueratosis

  - description: Es una afección comúnmente conocida como uña encarnada. Ocurre cuando el borde lateral o anterior de la uña, generalmente del primer dedo del pie (dedo gordo), se clava en la piel circundante, causando inflamación, dolor, enrojecimiento e incluso infección si no se trata a tiempo.
    title: UÑAS ENCARNADAS 
    subtitle: (ONICOCRIPTOSIS)
    picname: unas_encarnadas_onicocriptosis

  - description: Es una infección fúngica que afecta la piel de los pies, especialmente entre los dedos. Se manifiesta con descamación, enrojecimiento, picazón, grietas o ampollas, pudiendo extenderse a las plantas y los bordes de los pies.
    title: HONGOS EN EL PIE
    subtitle:  (PIE DE ATLETA)
    picname: hongos_pie_atleta

  - description: Es una lesión cutánea causada por el virus del papiloma humano (VPH). Aparece como una protuberancia en la planta del pie, a menudo con puntos negros (capilares trombosados) y rodeada de piel endurecida, causando dolor al presionarla.
    title: VERRUGA PLANTAR
    subtitle:  (PAPILOMA)
    picname: verruga_plantar_papiloma

  - description: Son afecciones que provocan el engrosamiento, decoloración, fragilidad y deformidad de las uñas, generalmente en los pies, debido a la invasión de dermatofitos, levaduras u otros hongos.
    title: INFECCIONES POR HONGOS A NIVEL DE UÑAS
    subtitle: 
    picname: infecciones_hongos_unas

# Build settings
markdown: kramdown
permalink: pretty